export interface AdvancedSearch {
     createdDateFrom:Date,
     createdDateTo:Date,
     updatedDateTo :Date,
     updatedDateFrom :Date,
     createdBy :string,
     updatedBy :string,
     id :number,
     statusId :number,
     customerName:string,
     frameName:string,
     governorateId:number,
     centralId:number,
     problemTypeId:number,
     problemLocationId:string,
     circleNumber:number,
     port:string,
     custommerAddress:string,
     customerNumber:string,
     powerConfirmation:string,
     ticketNumber:string
}
